### ISSUE TITLE
Error when using popup window layout

### ISSUE THREAD

**Issue by orlangure** [junegunn/fzf.vim#1028] opened 2020-05-14 15:12 UTC
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

After updating vim to 8.2.750, fzf.vim stopped working in preview window.

Commands like `Ag` work with minimal configuration, but break after using the following:

```
  let g:fzf_layout = { 'window': { 'width': 0.8, 'height': 0.5 } }
```
```
Error detected while processing function fzf#vim#ag[8]..fzf#vim#ag_raw[4]..fzf#vim#grep[24]..<SNR>25_fzf[18]..fzf#run[58]..<SNR>23_execute_term:
line   70:
E863: Not allowed for a terminal in a popup window
```

**Comment by mckellyln** [comment] 2020-05-14 19:11
I brought this up also with the vim dev group and others have mentioned similar there.  The usage of a terminal in a popup window was made more strict in vim in a recent commit.  I am not sure how to work around it yet.  In the meantime I changed to using a tmux popup or vim split layout.

**Comment by junegunn** [comment] 2020-05-15 01:26
Duplicate of https://github.com/junegunn/fzf/issues/2038

**Closed by junegunn** 2020-05-15 01:26 UTC
