### ISSUE TITLE
"Failed to read /dev/tty" after Ubuntu update

### ISSUE THREAD

**Issue by barndon** [junegunn/fzf.vim#758] opened 2019-01-29 20:02 UTC
- Category
    - [ ] Question
    - [x ] Bug
    - [ ] Suggestion
- OS
    - [x ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x ] Neovim

After an `apt upgrade` to Ubuntu 18.04 this morning and using this neovim invocation:

```vim -V20vimlog -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)```

...the `:FZF` command produces only a brief "Failed to read /dev/tty" error message.  The vimlog is attached.

The fzf binary works as expected outside of vim.

Neovim version:
```
$ vim -version
NVIM v0.3.1
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-M0l_b5/neovim-0.3.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-M0l_b5/neovim-0.3.1/build/config -I/build/neovim-M0l_b5/neovim-0.3.1/src -I/usr/include -I/build/neovim-M0l_b5/neovim-0.3.1/build/src/nvim/auto -I/build/neovim-M0l_b5/neovim-0.3.1/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
FZF version:
```
$ ~/.fzf/bin/fzf --version
0.17.5 (b46227d)
```

[vimlog.txt](https://github.com/junegunn/fzf.vim/files/2809433/vimlog.txt)

**Comment by indeedwatson** [comment] 2019-01-30 01:58
Having the same issue on arch.

**Comment by rtucek** [comment] 2019-01-30 02:15
Same here - I nailed it down to the most recent released Ubuntu 18.04 kernel update (v4.15.0-44).
After booting the previous kernel, the error disappeared.

**Comment by samiconductor** [comment] 2019-01-30 15:17
Also getting the error. Same kernal version as @rtucek 

```sh
$ uname -r
4.15.0-44-generic
```

The weird part is when I run the command in a terminal that `fzf.vim` is attempting to run, I'll get a sequence of about 5-10 failures followed by it working as expected a few times then back to failures.

```sh
$ /home/sam/.vim/var/plugins/fzf/bin/fzf  --multi --prompt ~/P/806Apps/ --expect=ctrl-v,ctrl-x,ctrl-t --height=21 > /tmp/vH3m0Nr/1
Failed to read /dev/tty
```

**Comment by indeedwatson** [comment] 2019-01-30 15:35
What's odd is that I'm on kernel 5.0.0 and the issue started at the same time as it did for 4.15 on ubuntu.

**Comment by barndon** [comment] 2019-01-30 19:37
To @samiconductor's point, I found that if I run vim under strace:
```
strace -fo ./vim.trace vi
```
...vim is slowed down significantly due to the tracing and `:FZF` works correctly every time.  Smells like a race condition.

**Comment by cfebs** [comment] 2019-01-31 02:47
Same issue here with `4.15.0-44-generic`. Also confirming booting back to `4.15.0-43-generic` fixed.

**Comment by rtucek** [comment] 2019-01-31 12:01
Meanwhile Ubuntu has released `v4.15.0-45` but it doesn't resolve the issue :/
If fixed some other bugs that affected me (https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1813663).
Sticking with `v4.15.0-43`

**Comment by wm8120** [comment] 2019-01-31 20:24
Same issue here. But it works if I used the vim in tmux.

**Comment by junegunn** [comment] 2019-02-01 00:44
Duplicate of https://github.com/junegunn/fzf/issues/1486

**Closed by junegunn** 2019-02-01 00:44 UTC
