### ISSUE TITLE
QUESTION - Neovim one button escape bind

### ISSUE THREAD

**Issue by AdamBD** [junegunn/fzf.vim#1358] opened 2022-01-22 15:01 UTC
Hello,

I am using fzf.vim with nvim and fzf opens in a terminal buffer. In order to close the buffer I need to use <ESC> to return to normal mode and then :q to close the buffer.

I am trying to simply have <ESC> close the buffer completely. Is there a way to do this easily?

**Comment by junegunn** [comment] 2022-01-23 16:02
Duplicate of https://github.com/junegunn/fzf.vim/issues/1213

**Closed by junegunn** 2022-01-23 16:02 UTC
