### ISSUE TITLE
FZF vim popup overflows 

### ISSUE THREAD

**Issue by blayz3r** [junegunn/fzf.vim#1032] opened 2020-05-18 17:35 UTC
- [X ] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [ X] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [X ] I have read through the manual page of fzf (`man fzf`)
- [X ] I have searched through the existing issues

One of the recent changes to the FZF popup causes the popup to overflow 
![image](https://user-images.githubusercontent.com/12205650/82242759-661c2800-990c-11ea-817b-5330ba808c01.png)

Similar to https://github.com/vim/vim/issues/5802

**Comment by blayz3r** [comment] 2020-05-19 18:00
@lacygoill any thoughts?

**Comment by lacygoill** [comment] 2020-05-19 18:39
I can't reproduce; maybe because the issue is specific to Windows.
You could try to bisect fzf to find from which commit the issue appeared, and provide a minimal example.

Here's an example of minimal vimrc:

    set rtp-=~/.vim rtp-=~/.vim/after rtp^=~/.vim/plugged/fzf.vim rtp^=~/.fzf
    let source = range(char2nr('a'),char2nr('z'))->map({_,v -> nr2char(v)})
    nno <c-b> :call fzf#run(fzf#wrap({'source': source, 'sink': {line -> execute('echom "you chose"'..string(line), '')}}))<cr>
    let g:fzf_layout = {'window': {'width': 0.9, 'height': 0.6}}

You may need to adapt the paths to the directories when setting the runtimepath, so that they match a Windows system.  Write the code in a file, then start Vim with:

    $ vim -Nu /path/to/vimrc

Press `C-b` and see whether the contents still overflows.

A few commits have been pushed on the fzf repo lately; maybe one of them has fixed the issue; make sure to be on master.

**Comment by blayz3r** [comment] 2020-05-31 18:01
I think the issue is that this function https://github.com/junegunn/fzf/blob/ace92ba281669df7f1d5c434789c454e98dde45b/plugin/fzf.vim#L835 needs:

```vim
            \ 'minheight': height,
            \ 'maxheight': height,
```
@lacygoill you made a comment to the contrary here https://github.com/vim/vim/issues/5802#issuecomment-600212217

**Comment by lacygoill** [comment] 2020-05-31 18:06
On Linux it is/was not needed.  But maybe it is needed on Windows; I don't have a Windows system to test but it may very well be necessary.  If that's the case, close this issue and open a new one on the fzf repo and submit a PR to fix the issue.

In any case, adding these 2 lines should not break anything on Linux, so it fixes an issue on Windows, there's no reason it won't be merged.

**Comment by blayz3r** [comment] 2020-05-31 18:07
> 
> 
> On Linux it is/was not needed. But maybe it is needed on Windows; I don't have a Windows system to test but it may very well be necessary. If that's the case, close this issue and open a new one on the fzf repo and submit a PR to fix the issue.
> 
> In any case, adding these 2 lines should not break anything on Linux, so if it fixes an issue on Windows, there's no reason it won't be merged.

Thanks, I tested it and adding 'maxheight': a:opts.height fixes the issue

**Closed** 2020-07-17 07:58 UTC
