### ISSUE TITLE
Do you have a plan to support ripgrep?

### ISSUE THREAD

**Issue by airhuman** [junegunn/fzf.vim#468] opened 2017-10-17 02:40 UTC
Hi Junegunn.
I like your fzf.vim plugin and I use it every single day.
Recently I found that ripgrep is faster than ag(the_silver_searcher).
Do you have a plan to support ripgrep?
Thank you.

**Comment by junegunn** [comment] 2017-10-17 04:11
You can already use rg with fzf.

https://github.com/junegunn/fzf.vim#advanced-customization

Note that the current version of ripgrep has [an issue](https://github.com/BurntSushi/ripgrep/issues/200) which makes it not the best companion for fzf. It should be fixed in the next release.

**Closed by junegunn** 2017-10-17 04:11 UTC

**Comment by airhuman** [comment] 2017-10-17 07:31
Thanks for your reply.

**Comment by aleksandersumowski** [comment] 2017-10-23 14:41
The issue is now fixed:

https://github.com/junegunn/fzf/commit/5784101beabcacfc86938f17ee3f2051e3b59816

**Comment by airhuman** [comment] 2017-10-24 02:26
It works well.

Thank you.
