### ISSUE TITLE
Opening file through :Files hangs sometimes

### ISSUE THREAD

**Issue by adelbertc** [junegunn/fzf.vim#287] opened 2017-01-10 19:39 UTC
- Category
    - [X] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [X] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [X] Neovim

On Mac OS in Terminal.app, running Neovim in a terminal through tmux, with the following plugins:

```
Plug 'altercation/vim-colors-solarized'

Plug 'junegunn/fzf', { 'dir': '~/.fzf-vim', 'do': './install --bin' }
Plug 'junegunn/fzf.vim'

function! DoRemote(arg)
  UpdateRemotePlugins
endfunction
Plug 'Shougo/deoplete.nvim', { 'do': function('DoRemote') }

Plug 'scrooloose/nerdtree'
Plug 'godlygeek/tabular'
Plug 'bling/vim-airline'
Plug 'tpope/vim-fugitive'

Plug 'idris-hackers/idris-vim'

Plug 'derekwyatt/vim-scala'
```

When I run `:Files<cr>`, select a file and hit `Enter`, sometimes (I have not yet identified any sort of pattern) Neovim will just hang for a couple seconds before finally opening the file. Any ideas?

**Comment by junegunn** [comment] 2017-01-29 17:12
I have no idea. If the problem is not reproducible using the minimal configuration provided in the issue template (https://raw.githubusercontent.com/junegunn/fzf.vim/master/.github/ISSUE_TEMPLATE.md), it's probably caused by another plugin.

**Comment by adelbertc** [comment] 2017-02-25 01:05
OK so I narrowed it down to this line in my init.vim:

`let $FZF_DEFAULT_COMMAND = 'find * -type f -not -path "*/target/*"'`

Which makes sense that it would be the one line in my config that touches FZF. However what's weird is that it appears to hang **after** I've selected the file I want.

I changed it to use ripgrep via:

`let $FZF_DEFAULT_COMMAND = 'rg --files --no-messages'`

and now it completes pretty fast.

**Comment by junegunn** [comment] 2017-02-25 14:25
I see, I'll close this then.

**Closed by junegunn** 2017-02-25 14:25 UTC

**Comment by abarax** [comment] 2017-05-11 01:57
I am also having this problem. What is essentially happening is that the file will not open until your FZF command has finished running i.e. the loading symbol stops spinning.  

This happens regardless of the FZF command being run (find, ag, rg).  Upon opening a file it will just hang until the underlying command completes. Once the command completes the file opens.  This is particularly evident when using :Find in a large directory of files.

Is there a way to change this behaviour so that if you immediately wish to open a file before the :Find command completes it will just terminate the executing :Find command and open the selected file?

**Comment by junegunn** [comment] 2017-05-17 16:29
It works for me as expected, non-blocking.
