### ISSUE TITLE
Some fzf commands hide alternate buffer

### ISSUE THREAD

**Issue by yevhen-m** [junegunn/fzf.vim#265] opened 2016-12-08 15:55 UTC
#
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Some fzf commands hide alternate buffer if I use `{'window': 'enew'}` layout setting. For instance, `BLines`, `BTags`, `Tags` commands. Is it possible to fix this issue?
By the way, `Files` command works properly, alternate buffer is there as expected.

**Comment by junegunn** [comment] 2016-12-10 03:54
I'm not sure what you're describing. Can you elaborate and provide the steps to reproduce?

**Comment by yevhen-m** [comment] 2016-12-10 09:54
@junegunn sure.
ubuntu/osx, neovim 0.2.0-dev

`let g:fzf_layout = { 'window': 'enew' }` -- this has to be in init.vim (I want fzf buffers be opened in the current active window).

Start nvim, open a file, then another one, ensure you can switch between alternate buffers (`C-^`). Then for instance do `:BLines` (I don't have any prefix set for fzf commands) and jump to any line, or just close fzf buffer with `C-c`. Now, when I try to switch to alternate buffer, I get vim error `E23: No alternate file`. Instead, I want to go to the buffer, that was alternate before I executed `:BLines`.

**Comment by junegunn** [comment] 2016-12-11 12:58
Hmm, I see. When fzf is open, it becomes the primary buffer and the previous buffer becomes the alternate file, and the other buffer that was previously marked as alternate file is pushed away.

I don't know if there a way to fix it. Is there a way to manually set the alternate file?

**Comment by yevhen-m** [comment] 2016-12-11 13:13
https://github.com/tpope/vim-vinegar/issues/25
Does this help?

**Comment by junegunn** [comment] 2016-12-11 13:28
`let g:fzf_layout = {'window': 'keepalt enew'}` combined with some fixes on fzf plugin should help.

**Comment by junegunn** [comment] 2016-12-11 13:31
Hmm, looks like fzf can force `keepalt` so that specifying it in `g:fzf_layout` is not necessary.

**Comment by junegunn** [comment] 2016-12-11 13:36
Should be fixed now (keepalt in fzf_layout is not necessary). Thanks for the report.

**Closed** 2016-12-11 13:35 UTC

**Comment by yevhen-m** [comment] 2016-12-11 17:47
@junegunn thanks a lot. I love this layout.
