### ISSUE TITLE
first keypress skipped when opening buffer in gvim

### ISSUE THREAD

**Issue by andrewrk** [junegunn/fzf.vim#506] opened 2017-11-15 18:58 UTC
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

in gvim, when I use fzf, and open a new file, it looks like I've opened the file, but the next keypress is skipped, leading to mistyping.

This is a regression as of a newer vim and/or fzf-vim which uses a different window strategy for displaying the fzf buffer.

in terminal vim, everything works as expected.

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan  1 1970 00:00:01)

I don't know the fzf version, I can find out if it helps.

**Comment by junegunn** [comment] 2017-11-16 00:59
Duplicate of https://github.com/junegunn/fzf/issues/1103.

**Closed by junegunn** 2017-11-16 00:59 UTC

**Comment by andrewrk** [comment] 2017-11-16 01:01
Thanks. I didn't find the issue when I searched. Hopefully this duplicate issue title can lead someone else to the issue who uses the search terms I did :-)
