### ISSUE TITLE
Fzf freezes using Neovim appimage

### ISSUE THREAD

**Issue by danihodovic** [junegunn/fzf.vim#521] opened 2017-11-25 13:44 UTC
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [ ] Neovim

A detailed bug report can be found here: https://github.com/neovim/neovim/issues/7620

**Comment by stsewd** [comment] 2017-11-26 12:52
I'm having the same problem.

I think this is a duplicate of #505

**Closed** 2018-06-26 09:59 UTC
Labels: duplicate

**Comment by justinmk** [comment] 2018-07-17 16:52
https://github.com/neovim/neovim/issues/8104 was fixed in Nvim 0.3.1 (prerelease).
