### ISSUE TITLE
Preview not works if file name contains spaces

### ISSUE THREAD

**Issue by dtcyganok** [junegunn/fzf.vim#554] opened 2017-12-24 18:41 UTC
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

**Comment by janlazo** [comment] 2018-01-02 01:25
Duplicate of #493?

**Closed** 2018-01-02 09:21 UTC
