### ISSUE TITLE
How to install fzf using Vundle

### ISSUE THREAD

**Issue by abbood** [junegunn/fzf.vim#457] opened 2017-09-29 13:03 UTC
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

I already use Vundle as a vim plugin manager.. and I've already installed fzf using homebrew:

    $ which fzf
    /usr/local/bin/fzf

but when I run vim and type `Files` I get:

```
Error detected while processing function fzf#vim#files[15]..<SNR>47_fzf[18]..<SNR>47_wrap:
line   12:
E117: Unknown function: fzf#wrap
E15: Invalid expression: fzf#wrap(a:name, opts, a:bang)
line   14:
E121: Undefined variable: wrapped
E15: Invalid expression: wrapped
Error detected while processing function fzf#vim#files[15]..<SNR>47_fzf:
line   18:
E117: Unknown function: fzf#run
E15: Invalid expression: fzf#run(s:wrap(a:name, merged, bang))
Press ENTER or type command to continue

```

What do I do?

**Comment by junegunn** [comment] 2017-09-29 15:07
Duplicate of #456

**Closed by junegunn** 2017-09-29 15:07 UTC
Labels: duplicate
