### ISSUE TITLE
Popup window error when using vim 8.2-814

### ISSUE THREAD

**Issue by jackysee** [junegunn/fzf.vim#1046] opened 2020-06-05 03:24 UTC
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Using vim version
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 23 2020 22:02:57)
Included patches: 1-814
```

When configured with popup windows:
```
let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.8 } }
```

Running `:Files` has this error
![image](https://user-images.githubusercontent.com/30516/83832937-56c71800-a71d-11ea-9d34-3df8f4132360.png)

Gif:
![ElsHWQBoOy](https://user-images.githubusercontent.com/30516/83833610-efaa6300-a71e-11ea-87a4-ec42047f448d.gif)

**Comment by junegunn** [comment] 2020-06-07 01:19
Duplicate of https://github.com/junegunn/fzf/issues/2038. Make sure that you have the latest version of the Vim plugin file from the main `fzf` (not `fzf.vim`)

**Closed by junegunn** 2020-06-07 01:19 UTC
