### ISSUE TITLE
fzf output garbled in MacVim terminal

### ISSUE THREAD

**Issue by chew-z** [junegunn/fzf.vim#470] opened 2017-10-21 11:01 UTC
- Category
    - [ ] Question
    - [ x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ x] Vim
    - [ ] Neovim

I have a problem with terminal in MacVim. I think it is related to handling of alternative screen.

In short I have written a plugin [iTunes.vim](https://github.com/chew-z/itunes.vim) based on fzf. Since latest update of fzf it has started to work inside MacVim (which is great feature by itself, no more glue necessary) but also started garbling output. 

As you can see in the screenshot content of preview window is somewhere in the middle of window. And there is something like a mirror image below with similar contents (and borders of preview window) but I cannot scroll there. 

When the output is longer it looks like overwritten on top of previous lines not scrolled.

I also have to press Esc twice to exit and close terminal window.

Perhaps the reason is that I am using "enter:execute-silent" and there is some qui pro quo with alternative screen?

<img width="847" alt="screen shot 2017-10-21 at 18 00 42" src="https://user-images.githubusercontent.com/2264679/31851145-d977e5d6-b689-11e7-810e-c8968d391c11.png">

<img width="851" alt="screen shot 2017-10-21 at 17 44 27" src="https://user-images.githubusercontent.com/2264679/31851016-ce21fd5e-b687-11e7-8b2b-cdf5cfc46190.png">

I have experimented with removing preview window but no luck. Output is still garbled.

It works OK in terminal Vim and used to work with MacVim-terminal glue. 

This is part of my code that is calling fzf:

```
    call fzf#run({
                \ 'source': s:tracks,
                \ 'sink':   function('s:handler'),
                \ 'options': '-i' .
                \ ' --header "Enter to play track Esc to exit ? toggles preview ['  . l:online . ']"' .
                \ ' --bind "enter:execute-silent(echo -n {} | gsed -e ''s/^\(.*\) | \(.*\) | \(.*\) | \(.*$\)/\"\1\" \"\4\"/'' | xargs osascript -l JavaScript ' .  s:files.Play . ')" ' .
                \ ' --preview="echo -e {} | tr ''|'' ''\n'' | sed -e ''s/^ //g'' | tail -r " ' .
                \ ' --preview-window down:4:wrap' .
                \ ' --bind "?:toggle-preview"'
                \ })
```

How to reproduce? Well installing my plugin and running some search in MacVim - I think.

**Comment by chew-z** [comment] 2017-10-21 11:19
OK, I have played with some other tools and it seems not related particularly to my plugin.

After using `command! -bang -nargs=* MRU call fzf#vim#history(fzf#vim#with_preview())` and scrolling up and down couple of times output gets garbled and looks like this.

<img width="865" alt="screen shot 2017-10-21 at 18 16 42" src="https://user-images.githubusercontent.com/2264679/31851253-60371eaa-b68c-11e7-833e-7ad617f97318.png">

**Comment by junegunn** [comment] 2017-10-21 11:31
The terminal emulator of vim is relatively new, and I wouldn't be surprised if it doesn't work as expected or shows some glitches. I don't think there's anything fzf can do to workaround the issue. Try updating your MacVim to the latest and see if it helps.

By the way, `:call fzf#vim#history(fzf#vim#with_preview())` seems to work fine for me.

**Comment by chew-z** [comment] 2017-10-21 12:20
I think I have got it. 

I have been using [very nice plugin vim-workspace](https://github.com/bagrat/vim-workspace) for helping with buffers. 

It requires `set guioptions-=e` to show buffers tab style in .gvimrc for MacVim. 
Setting `set guioptions+=e` hides IDE-style tab and show MacVim tabs but also made problems with terminal output gone. Now everything is drawn and redrawn as it should.

Pity my two favorite tools conflict each other. I will open issue with [vim-workspace](https://github.com/bagrat/vim-workspace)

You can close the issue. Thank you for fzf.

**Comment by junegunn** [comment] 2017-10-22 04:22
Thanks for the update.

**Comment by CJBridges** [comment] 2017-10-30 04:09
Just to add another "me-too" to this, I see similar results with MacVim (latest version - `Custom Version 8.0.1207 (140)`).  Terminal vim and running fzf directly work great.

Here's a gif example in MacVim proper (it gets worse than that, but it was a clean enough example):
![filestexthangingout](https://user-images.githubusercontent.com/7446001/32154311-0c97b388-bced-11e7-9e63-228499eac879.gif)

If I did want to report an issue upstream (c.f. "The terminal emulator of vim is relatively new"), where's the best place to do that?

**Comment by benvds** [comment] 2017-11-01 12:42
I'm having the same issue and am not using vim-workspace. Also using MacVim Version 8.0.1207 (140).

When running vim via the terminal the issue disappears though.

**Comment by CJBridges** [comment] 2017-11-11 15:49
Can this issue please be reopened, or a better pointer provided for how to report the issue with other related projects?

**Comment by semanser** [comment] 2017-11-15 09:29
The same issue with the latest versions of MacVim (Custom Version 8.0.1272 (142)) and fzf 0.17.1

**Comment by junegunn** [comment] 2017-11-15 14:49
I'll keep this open, but there's nothing I can do about it. For the time being, you'll have better experience with GUI versions of Neovim such as VimR.

**Comment by CJBridges** [comment] 2017-11-15 21:57
@junegunn should we be reporting this with the MacVim project?  I'm mostly looking to have a path to push the problem upward to the project that can deal with it, and not to raise issues with improper projects.

**Comment by junegunn** [comment] 2017-11-19 03:28
I'm not sure if it'a an issue of MacVim or an issue of upstream Vim itself. You can have terminal Vim also use terminal buffers by setting something like `let g:fzf_layout = {'window': 'botright split'}`. See if the problem is reproducible on terminal Vim.

**Comment by semanser** [comment] 2017-11-19 17:59
@junegunn Looks like problem appears only in the MacVim version. I have tried in the terminal and didn't get any problems.

**Comment by junegunn** [comment] 2017-11-19 18:23
Yeah, my experience is similar. The terminal emulator of Macvim seems to have some issues with ANSI escape sequences and you don't need fzf to observe rendering glitches. Open a terminal buffer in Macvim (`:terminal`), and try something like the follows.

```sh
gem install lolcat

# repeat 
while true; do ls -al | lolcat; sleep 1; done
```

<img width="770" alt="screen shot 2017-11-20 at 3 22 46 am" src="https://user-images.githubusercontent.com/700826/32993877-1ad8363c-cda2-11e7-9dfb-22fb30b00094.png">

**Comment by junegunn** [comment] 2017-11-20 18:11
I'll close this again since this is a duplicate of https://github.com/junegunn/fzf/issues/1108

Also see https://github.com/macvim-dev/macvim/issues/579

**Closed by junegunn** 2017-11-20 18:11 UTC

**Comment by junegunn** [comment] 2017-11-20 18:13
https://github.com/macvim-dev/macvim/issues/599 also seems to be related.
