### ISSUE TITLE
validate_layout() does not take --reverse into account.

### ISSUE THREAD

**Issue by mrbiggfoot** [junegunn/fzf.vim#341] opened 2017-03-20 20:24 UTC
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

```
:echo g:fzf_layout
{'options': '--reverse', 'down': '~40%'}

:History
Error detected while processing function <SNR>16_history[7]..fzf#vim#history[1]..<SNR>50_fzf[18]..<SNR>50_wrap[8]..fzf#wrap[30]..<SNR>15_validate_layout:
line    3:
E605: Exception not caught: Invalid entry in g:fzf_layout: options (allowed: window, up, down, left, right). Use $FZF_DEFAULT_OPTS.
Error detected while processing function <SNR>16_history[7]..fzf#vim#history[1]..<SNR>50_fzf[18]..<SNR>50_wrap[8]..fzf#wrap:
line   30:
E171: Missing :endif
Error detected while processing function <SNR>16_history[7]..fzf#vim#history[1]..<SNR>50_fzf[18]..<SNR>50_wrap:
line    8:
E171: Missing :endif
Error detected while processing function <SNR>16_history:
line    7:
E171: Missing :endif
```

**Comment by mrbiggfoot** [comment] 2017-03-20 20:41
Looks like it has stopped accepting --reverse as a valid option. Why is that?

**Comment by mrbiggfoot** [comment] 2017-03-20 20:55
Offending commit id: 111d1934c49ac22cf84abf0ada9c24f091fc38cd

**Comment by junegunn** [comment] 2017-03-21 00:03
Duplicate of #317 and #327. `g:fzf_layout` was never designed to take options key. Where did you get the idea?

**Closed by junegunn** 2017-03-21 00:03 UTC

**Comment by mrbiggfoot** [comment] 2017-03-21 00:28
@junegunn how do I get --reverse behavior in the History window then?

**Comment by mrbiggfoot** [comment] 2017-03-21 00:31
Checked out the other two tickets. Will try $FZF_DEFAULT_OPTS way.

**Comment by junegunn** [comment] 2017-03-21 01:42
It seems to me that all you guys ended up with more or less the same type of misconfiguration. Did someone suggested the idea?

**Comment by mrbiggfoot** [comment] 2017-03-21 01:56
I wish I could remember... I must have googled it somewhere.

**Comment by mrbiggfoot** [comment] 2017-03-21 02:04
Though I must admit neither way seems elegant to me. I'd prefer to have a function call that takes a dictionary of arguments for position, orientation, key mappings, etc. Setting g:fzf_layout or $FZF_DEFAULT_OPTS is cumbersome. Anyway, I've worked around it. Thanks for fzf @junegunn!

**Comment by junegunn** [comment] 2017-03-21 03:34
Well, you can do that if you want.
See https://github.com/junegunn/fzf.vim#advanced-customization
