### ISSUE TITLE
in Vim8, start fzf in popup window still not work

### ISSUE THREAD

**Issue by doums** [junegunn/fzf.vim#959] opened 2020-03-01 11:49 UTC
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

I use VimPlug, in my `.vimrc` I have the following:
```
Plug 'junegunn/fzf', { 'do': './install --bin' }
Plug 'junegunn/fzf.vim'

...

let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.6 } }
```

:version
VIM - Vi IMproved 8.2 (2019 Dec 12, compilé Jan 26 2020 11:45:38)
Rustines incluses : 1-148
Compilé par Arch Linux

When I try to open fzf via :Files for example I get the following error and an empty popup window is open.
```
Error detected while processing function fzf#vim#files[15]..<SNR>83_fzf[18]..fzf#run[58]..<SNR>28_execute_term[3]..<SNR>28
_split[10]..<SNR>28_popup[50]..<SNR>28_create_popup :
ligne    3 :
E278: Cannot put terminal buffer in pop-up window
```

**Comment by junegunn** [comment] 2020-03-01 11:53
Duplicate of #943. You need a newer version of Vim.

**Closed by junegunn** 2020-03-01 11:53 UTC

**Comment by doums** [comment] 2020-03-01 12:02
A newer version of Vim ? I'am already on version 8.2, with feature for popup window enabled.
I don't think this is a problem with my vim version.

**Comment by junegunn** [comment] 2020-03-01 12:08
Please read the linked issue.

**Comment by doums** [comment] 2020-03-01 12:19
Ok I will wait for Archlinux to update vim then, thank you.

**Comment by srijanshetty** [comment] 2020-03-02 07:29
@doums: Alternatively you could compile vim from source, I was stuck on an older vim version and had to go the compiling from source way to get popup support.

**Comment by doums** [comment] 2020-03-02 08:41
@srijanshetty thank for the tip but yup I know.

But I trust Archlinux about their package maintenance, and my current version is not old but recent (compiled Jan 26 2020). It just miss a few latest patches. They will be added soon ;)

**Comment by srijanshetty** [comment] 2020-03-02 17:42
@doums: the beauty of arch :smile:, I've given up on Ubuntu keeping packages upto date and hence compile most of my dependencies from source :cry:

**Comment by damofthemoon** [comment] 2020-03-02 18:06
Personally I moved to Neovim few weeks ago and use its appimage. Pretty good and confortable to avoid this issue and deploy it easily :)

**Comment by doums** [comment] 2020-03-02 21:22
AppImage is nice, but not handy. You have to download yourself the new one each time a new release is out which involves to keep an eye on them, plus the fact that you certainly need to create some desktop entry for that AppImage etc..

By the way, Archlinux has updated Vim today @srijanshetty :smile:
wait is over
```
:version
VIM - Vi IMproved 8.2 (2019 Dec 12, compilé Mar  1 2020 17:21:03)
Rustines incluses : 1-343
```
