### ISSUE TITLE
Navigate to open buffer/window?

### ISSUE THREAD

**Issue by trusktr** [junegunn/fzf.vim#77] opened 2016-01-23 07:39 UTC
Is there a way to use Buffers or Windows to navigate to the existing window (instead of new tab or split)?

**Comment by junegunn** [comment] 2016-01-23 07:46
Press enter? Not sure if I understood your question.

**Comment by trusktr** [comment] 2016-01-23 08:13
Pressing enter opens the file in the current window, but leaves the existing windows (which may be in another tab) open. I'd like to switch to that window/tab instead of making a new window.

**Comment by junegunn** [comment] 2016-01-23 08:19
`:Windows` command does exactly that.

**Comment by trusktr** [comment] 2016-01-23 09:32
Indeed, sorry about that. Don't know why I thought that. It works the first time, but after that I'm getting an error like this with both Windows and Buffers:

```
Error detected while processing function 267:                                                                                                                                      
line   30:                                                                                                                                                                         
E121: Undefined variable: ret                                                                                                                                                      
Press ENTER or type command to continue                                                                                                                                            
Error detected while processing function 267:                                                                                                                                      
line   30:                                                                                                                                                                         
E116: Invalid arguments for function <SNR>49_popd                                                                                                                                  
Press ENTER or type command to continue                                                                                                                                            
```

**Comment by junegunn** [comment] 2016-01-23 10:50
Never had that before. What's the `:version`? Please test again with minimal vim configuration; no other plugins.

**Comment by iclanzan** [comment] 2016-02-09 17:39
I am also getting a similar error:
```
Error detected while processing function 267:
line  30:
E121: Undefined variable: ret
Press ENTER or type command to continue
```

**Comment by junegunn** [comment] 2016-02-09 17:52
@iclanzan Please provide the steps to reproduce the problem.

**Comment by iclanzan** [comment] 2016-02-11 07:12
Unfortunately I can’t seem to be able to reproduce it reliably. I don’t know what triggers the problem, but after it happens once it keeps happening as long as I try to open a file in the current buffer. If I instead open it in a split window it works.

**Comment by iclanzan** [comment] 2016-02-11 23:20
I think I got it. The error is triggered when trying to open a file over an unsaved buffer.

**Comment by junegunn** [comment] 2016-02-12 03:30
Okay, I noticed that the problem is reproducible on Neovim when `hidden` is unset. I can fix it to give a better error message.

**Comment by junegunn** [comment] 2016-02-12 03:34
Should be fixed now. Thanks for the feedback.

**Closed by junegunn** 2016-02-12 03:34 UTC

**Comment by iclanzan** [comment] 2016-02-12 03:40
Cool, thanks!
