### ISSUE TITLE
FZF plugin sometimes not responding to typing

### ISSUE THREAD

**Issue by bsander** [junegunn/fzf.vim#927] opened 2020-01-08 14:01 UTC
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Sometimes after opening FZF with the Files or Rg command, fzf is not responding to anything I type. Pressing Escape generates a keycode instead, and I have to C-c to exit the buffer. Retrying the same command immediately after usually results in FZF functioning perfectly fine. But apart from that, this issue appears to happen quite randomly.

Don't know what other relevant info I can provide at this stage, please let me know 🙂

![Screenshot 2020-01-07 at 15 09 11](https://user-images.githubusercontent.com/517850/71983414-02c80e00-3227-11ea-93f3-b9216be43060.png)

**Comment by junegunn** [comment] 2020-01-09 07:09
I haven't had the issue. Is it reproducible with the minimal config shown in the issue template?

**Comment by daogilvie** [comment] 2020-01-21 19:01
Hi @junegunn; thanks for maintaining fzf and this plugin, I'm really enjoying using them both!
That said, unfortunately I am experiencing the same issue as bsander, but it is not random — it happens to me in pretty much every invocation of `Rg` and `Ag`, but not of `Files`.

This _does_ happen with the minimal config. I am on Catalina 10.15.2, using NVIM v0.4.3. There are no error messages in `:messages`, and I can't see anything that looks obvious when I run with `-V9` logging (but I don't really know what I would be looking for).

Please let me know how I can help narrow this down.

**Comment by daogilvie** [comment] 2020-01-23 12:05
It keeps recurring. If you think of any useful information for debugging, let me know.

**Comment by xp-bar** [comment] 2020-01-23 14:52
I've been having this problem for a while - haven't been able to find any information out there on it - this is actually the first issue I've found.

My setup is basically:
- [alacritty](https://github.com/alacritty/alacritty) @ 0.4.0
- [tmux](https://github.com/tmux/tmux) @ 3.0a
- [neovim](https://github.com/neovim/neovim) @ 0.4.2

<details>
<summary>nvim install info</summary>
<pre>
<code>
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/config -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/src -I/usr/local/include -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/src/nvim/auto -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/include
Compiled by brew@Mojave-2.local

Features: +acl +iconv +tui
See ":help feature-compile"

system vimrc file: "$VIM/sysinit.vim"
fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.2/share/nvim"

Run :checkhealth for more info
</code>
</pre>
</details>


it seems all the `fzf.vim` commands randomly stop accepting input - even though the command is clearly running / not frozen (the file number is ticking up, neovim itself isn't frozen). The cli command will also sometimes hang in the same manner - but no prompt appears (vs. in nvim, where the files list shows up fine, but it doesn't accept any input)

When using `tmux`, I have noticed is that closing out that (tmux) window completely seems to solve the issue - but opening and closing neovim within the same (tmux) window / split doesn't seem to resolve the issue.

**Comment by heliostatic** [comment] 2020-01-29 21:43
I have the same setup as you @xp-bar -- tmux definitely exacerbates the issue, as I have a 100% repro with rg / `fzf#vim#grep` in tmux.

**Comment by heliostatic** [comment] 2020-01-29 21:49
@junegunn I have a consistent repro with the minimal vimrc:
https://dsc.cloud/66a285/CleanShot-2020-01-29-at-16.47.38.mp4

**Comment by heliostatic** [comment] 2020-01-30 14:35
Update: I was too impatient -- the file actually does open after ~40 seconds.
[![asciicast](https://asciinema.org/a/H6tJwcrLqideA3AeBSZNc1k3b.svg)](https://asciinema.org/a/H6tJwcrLqideA3AeBSZNc1k3b)

**Comment by heliostatic** [comment] 2020-01-30 14:53
Last update I think:
No repro under iTerm. Just Alacritty + Tmux for me. I'll file a bug in the Alacritty repo.

**Comment by heliostatic** [comment] 2020-01-30 20:13
Hmm, I can now repro under Terminal.app and iTerm, no tmux session.

Here's a debug log showing the issue: [debug.txt](https://github.com/junegunn/fzf.vim/files/4136023/debug.txt)

I used the minimal .vimrc but added verbose logging level 12:

```vim
set nocompatible hidden laststatus=2

set verbose=12
set verbosefile=debug.txt

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'junegunn/fzf', { 'do': './install --bin' }
Plug 'junegunn/fzf.vim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync
```

**Comment by sethfowler** [comment] 2020-01-31 20:27
It's unsurprising, since it's based on neovim, but FWIW I experience this issue frequently with VimR v0.31.0-337 as well.

**Comment by daogilvie** [comment] 2020-02-03 16:39
## Update

I have found that leaving the Rg results buffer open for 30s then closing with `Ctrl-C` does then make it work as expected (i.e responds to input as expected). It also then works straight away in new Vim sessions and terminals after doing this. I will try to have a look in some more detailed logs and see what might be happening.

**Comment by xp-bar** [comment] 2020-02-04 14:30
^ I still have this issue occasionally (about once a day, closing `tmux` window resolves it), so I'll do what I can to post any relevant info here

Speaking of relevant info, I have no idea where to start - haven't ever debugged anything like this before. Any specific log files I should be watching / submitting?

**Comment by junegunn** [comment] 2020-02-13 12:22
Hi, please test if https://github.com/junegunn/fzf/commit/5e1db9fdd31257bc807348983dd3ae690056e5e0 fixes the issue.

**Comment by heliostatic** [comment] 2020-02-13 14:20
> Hi, please test if [junegunn/fzf@5e1db9f](https://github.com/junegunn/fzf/commit/5e1db9fdd31257bc807348983dd3ae690056e5e0) fixes the issue.

Just installed from master and it appears the issue is resolved by https://github.com/junegunn/fzf/commit/5e1db9fdd31257bc807348983dd3ae690056e5e0

**Closed** 2020-02-14 01:11 UTC
