### ISSUE TITLE
:Files not working since recent Vim / Ubuntu changes

### ISSUE THREAD

**Issue by MeisterLLD** [junegunn/fzf.vim#759] opened 2019-01-31 20:16 UTC
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

 
Hi everyone. Without any notice, a few days ago :Files stopped working in Vim. The only explanation would be some recent changes in Vim or Ubuntu because
1. it still works in gvim
2. :History and :Buffer still work well
3. Bug is present with standard Ubuntu terminal but it works fine in other terminals (tmux for instance)

Here is the exact message :Files gives me

> Error running '/home/laurent/.fzf/bin/fzf'  '-m' '--prompt' '/home/laurent/' --expect=ctrl-v,ctrl-x,ctrl-t --height=22 > /tmp/v3AI
c5w/0

Same error with the minimal configuration. I have a very standard installation on Ubuntu, and I use Vundle (everything worked well until a few days ago).

Do you have any idea what is going on ?

EDIT : command **:FZF! works fine**, so I guess the problem has to do with split screen.

**Comment by robrobbins** [comment] 2019-01-31 20:30
+1

**Comment by MeisterLLD** [comment] 2019-01-31 21:14
@robrobbins  so I guess it is rather terminal related ! Did you also lose syntax color on standard Ubuntu term at the same time ?

**Comment by junegunn** [comment] 2019-02-01 00:44
Duplicate of https://github.com/junegunn/fzf/issues/1486

**Closed by junegunn** 2019-02-01 00:44 UTC
