### ISSUE TITLE
When open a file with fzf, $PWD isn't changed

### ISSUE THREAD

**Issue by iven** [junegunn/fzf.vim#70] opened 2016-01-11 07:15 UTC
I have `autochdir` option set. When I open a file use `split`, or with `ctrlp`, $PWD is automatically changed as expected. But with `fzf.vim`, it doesn't change.

**Comment by junegunn** [comment] 2016-01-11 08:29
Thanks for the report. But I can't seem to reproduce the problem. Check if the problem is reproducible with the following config:

```vim
call plug#begin('~/.vim/plugged')
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
call plug#end()

set autochdir
```

```sh
vim -Nu <(curl https://gist.githubusercontent.com/junegunn/3db3e26b85c76f76d889/raw/e574dc52f47005f3fa2ad67d3bdb455b7d31d01e/gistfile1.txt)
```

**Comment by iven** [comment] 2016-01-11 08:38
Yes, it's reproducible here. BTW, I'm using neovim 0.1.1, with `:PlugUpdate` succeeded.

**Comment by junegunn** [comment] 2016-01-11 08:41
Strange. Which command did you use? Please provide the exact steps to reproduce the issue.

**Comment by junegunn** [comment] 2016-01-11 08:44
Note that `$PWD` is not affected by `autochdir` with or without fzf. Check the output of `:pwd` or `:echo getcwd()` instead.

**Comment by iven** [comment] 2016-01-11 08:45
@junegunn I found that only `:GitFiles` command has this issue, `:Files` works as expected. The steps:

```
$ vim -Nu <(curl https://gist.githubusercontent.com/junegunn/3db3e26b85c76f76d889/raw/e574dc52f47005f3fa2ad67d3bdb455b7d31d01e/gistfile1.txt)
<:GitFiles>
// Select a file in the subfolder
<Enter>
<:pwd>
// $PWD remains the origin directory
```

**Comment by junegunn** [comment] 2016-01-11 09:05
Ah, I see what's going on. You'll see the same issue when you pass directory argument to `:Files` command. e.g. `:Files .`.

This should be fixed in the main repo.

**Comment by junegunn** [comment] 2016-01-11 09:18
https://github.com/junegunn/fzf/commit/b18db4733c635705b3aa052efe91472432727c58

The above commit should fix the problem. Thanks for the report.

**Comment by junegunn** [comment] 2016-01-11 09:21
Hmm, let me check a few more things.

**Comment by junegunn** [comment] 2016-01-11 16:31
It should work as expected now.

**Closed by junegunn** 2016-01-11 16:31 UTC
Labels: bug
