### ISSUE TITLE
Abort fzf search requires <Esc><Esc>

### ISSUE THREAD

**Issue by kiryph** [junegunn/fzf.vim#604] opened 2018-03-26 14:14 UTC
- Category
    - [ ] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim (macvim)
    - [ ] Neovim

Fuzzy file search and aborting work. After adding following augroup

```
augroup Myfzf
  autocmd! FileType fzf
  autocmd  FileType fzf set laststatus=0 noshowmode noruler
    \| autocmd BufLeave <buffer> set laststatus=2 showmode ruler
augroup END
```
I have to press `<Esc>` twice if I want to abort a search.

However, if I use `:History` and select a file, I always  have to press `<CR>` twice.

This only occurs in macvim (snapshot 146 which does not have any visual glitches when using fzf) not in terminal vim.

**Comment by jonleighton** [comment] 2018-04-27 01:53
I have the same problem, also in macvim. For example if I use `:Ag`, then it `<Esc>`, the suggestions go away and I am looking at a blank fzf window. If I wait around 5-10 seconds the window eventually closes. If I press any key then the window goes away (and vim does whatever it should do given the key I pressed).

**Comment by junegunn** [comment] 2018-04-27 02:51
I can reproduce the problem. And it looks like we can workaround the problem with the following patch for now.

```diff
diff --git a/plugin/fzf.vim b/plugin/fzf.vim
index 4659f85..b37d0a2 100644
--- a/plugin/fzf.vim
+++ b/plugin/fzf.vim
@@ -497,6 +497,9 @@ endif
 
 function! s:exit_handler(code, command, ...)
   if a:code == 130
+    if has('gui_running')
+      call feedkeys("\<esc>")
+    end
     return 0
   elseif a:code > 1
     call s:error('Error running ' . a:command)
```

But it would be better if Macvim could fix the issue. We could try to find a simple way to reproduce the case in Macvim only using terminal buffer without fzf to help the developers of Macvim.

**Comment by grillermo** [comment] 2018-04-27 17:40
I have the same problem but when selecting an item after hitting enter i have to hit it again or wait a few seconds
![gq0580uzoe](https://user-images.githubusercontent.com/761476/39376569-c0375a44-4a17-11e8-93ec-d0d87cca8c0f.gif)

@junegunn your help would be much appreciated

**Comment by junegunn** [comment] 2018-04-28 03:02
Does this patch help?

```diff
diff --git a/plugin/fzf.vim b/plugin/fzf.vim
index 4659f85..d8d42b1 100644
--- a/plugin/fzf.vim
+++ b/plugin/fzf.vim
@@ -496,6 +496,9 @@ else
 endif
 
 function! s:exit_handler(code, command, ...)
+  if has('mac') && has('gui_running')
+    call feedkeys("\<esc>", 'n')
+  endif
   if a:code == 130
     return 0
   elseif a:code > 1
```

**Comment by junegunn** [comment] 2018-04-28 03:08
The actual problem is easily reproducible with the following snippet.

```vim
function! OnExit(...)
  close
endfunction
call term_start('sleep 1', {'exit_cb': function('OnExit')})
```

Adding `redraw` after `close` helps, but the cursor stays in a weird place until you hit a key.

**Comment by jonleighton** [comment] 2018-05-19 04:43
Done: https://github.com/macvim-dev/macvim/issues/685 (hopefully I've described the issue correctly...)

**Comment by ichizok** [comment] 2018-06-27 03:32
This has been fixed in https://github.com/macvim-dev/macvim/commit/2a9f2b5bac9a6d1072d019b778dfff3ba7fea79f.
Please confirm MacVim snapshot-148 or later.

**Closed** 2018-06-27 03:50 UTC

**Comment by kiryph** [comment] 2018-06-27 10:10
I can confirm that for MacVim snapshot 149 my issue is resolved.

Thanks to @jonleighton, @ichizok and  @splhack for raising the issue on macvims issue tracker, actually writing a fix and merging the fix.

**Comment by creepinson** [comment] 2020-12-26 03:21
I'm having this same issue with ESC+ESC but its on Manjaro KDE Konsole.

**Comment by mert-microsoft** [comment] 2023-11-13 06:59
I have the same issue on Windows.

**Comment by jkulhanek** [comment] 2024-04-29 12:59
I have the same issue with vim 9.1 on using Alacrity on Ubuntu 22
