### ISSUE TITLE
Alignment issue when buffer numbers are above 1000

### ISSUE THREAD

**Issue by yuriescl** [junegunn/fzf.vim#1263] opened 2021-03-16 12:02 UTC
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

When buffer numbers are 1000 or above, `:Buffers` introduces a huge space on the item:

![image](https://user-images.githubusercontent.com/26092447/111305801-28745280-8636-11eb-854b-ba6c14715bf6.png)

**Comment by junegunn** [comment] 2021-03-16 13:04
Duplicate of #1237. It's fixed on master.

**Closed by junegunn** 2021-03-16 13:04 UTC

**Comment by junegunn** [comment] 2021-03-24 16:18
Fixed in caf7754
