### ISSUE TITLE
Command :Tags won't jump to tag in a modified buffer

### ISSUE THREAD

**Issue by Perlence** [junegunn/fzf.vim#134] opened 2016-04-25 12:20 UTC
If I make even a slightest change in a buffer and the try to jump to a tag in this buffer via `:Tags`, it won't go anywhere.

**Comment by junegunn** [comment] 2016-04-25 12:44
You need `set hidden` in your vimrc.

**Comment by Perlence** [comment] 2016-04-25 12:50
Unfortunately, `hidden` is already set. I should clarify that it won't be the case even if `hidden` is not set, because I'm trying to jump to a tag in a buffer that is currently visible.

**Comment by junegunn** [comment] 2016-04-25 13:22
> I'm trying to jump to a tag in a buffer that is currently visible.

It doesn't matter if the target buffer is visible or not. In order to open another buffer in the current window, `:Tags` has to hide the current buffer, and without `hidden`, it can't.

Anyway, I can't reproduce the problem when `hidden` is set. Please make sure that it's not caused by some other settings or plugins.

```vim
nvim -u <(cat << "EOF"
  call plug#begin('~/.vim/plugged')
  Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': 'yes \| ./install' }
  Plug 'junegunn/fzf.vim'
  call plug#end()
  set hidden
EOF)
```

**Comment by Perlence** [comment] 2016-04-25 13:54
The problem's still there. Here's what I'm trying to do:

[![Command :Tags won't jump to tag in a modified buffer](https://asciinema.org/a/9wq62hqsxa7g8t8irle31gfff.png)](https://asciinema.org/a/9wq62hqsxa7g8t8irle31gfff)

**Comment by junegunn** [comment] 2016-04-25 14:23
Ah, thanks, now I see what's going on here. Other commands in fzf.vim should have the save issue as this.

**Comment by junegunn** [comment] 2016-04-25 14:54
Should be fixed now, thanks for the report.

**Closed** 2016-04-25 14:54 UTC
Labels: bug

**Comment by Perlence** [comment] 2016-04-25 14:56
Thank you very much for quick response!

**Comment by junegunn** [comment] 2016-04-25 15:11
No problem. Sorry for not getting your point in the first place.
