### ISSUE TITLE
"Swap file already exists" dialog is hidden by fzf

### ISSUE THREAD

**Issue by SergioBenitez** [junegunn/fzf.vim#711] opened 2018-10-05 05:54 UTC
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS 10.13.6
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim v0.3.1 (with minimal config)

As the title suggests, at some point in the recent past, fzf started hiding the "Swap file already exists!" dialog that (neo)vim pops up when a swap file already exists. Instead of showing the dialog, fzf does nothing, seemingly hanging. Nevertheless, you can "interact" with the dialog as if it was there, so an [enter] or [o] or [e] gets you past the hang.

The GIF below shows the issue:

![fzf-issue](https://user-images.githubusercontent.com/1480321/46518303-61cef400-c828-11e8-85e4-117b2bcaf271.gif)

**Comment by junegunn** [comment] 2018-10-05 07:45
Thanks for the report. This is a duplicate of https://github.com/junegunn/fzf/issues/1365.

**Closed by junegunn** 2018-10-05 07:45 UTC
